import { execFileSync } from "node:child_process";
import { describe, expect, it } from "vitest";
import { sectionize } from "../../scripts/change-radar/sectionize";
import { diffSections } from "../../scripts/change-radar/diff";
import { buildPublicChangeEvent, retainBoundedHistory } from "../../scripts/change-radar/emit";
import { CHANGE_RADAR_SOURCE_REGISTRY } from "../../data/change-radar/registry";
import { hashNormalizedContent } from "../../scripts/change-radar-core.mjs";
import { discoverDetailed } from "../../scripts/change-radar/discover";
import { runRadar } from "../../scripts/change-radar/orchestrator";
import { parsePublicChangeEvent, parseSourceHealth } from "../../lib/change-radar/schema";
describe("Phase 3 radar contracts", () => {
  it("loads the real CLI through Node's strip-only TypeScript runtime", () => {
    expect(execFileSync(
      process.execPath,
      ["--experimental-strip-types", "scripts/change-radar/cli.ts", "validate"],
      { cwd: process.cwd(), encoding: "utf8" },
    )).toContain("Change Radar artifacts are schema-valid.");
  });
  it("uses hierarchical paths and occurrences", () => { const sections = sectionize("# A\n## Same\none\n## Same\ntwo\n# B\n## Same\nthree"); expect(sections.map((s) => [s.headingPath.join("/"), s.occurrence])).toEqual([["A",1],["A/Same",1],["A/Same",2],["B",1],["B/Same",1]]); });
  it("does not lose duplicate headings", () => { expect(diffSections("# A\n## X\none\n## X\ntwo", "# A\n## X\none\n## X\nchanged")).toMatchObject([{ type: "MODIFIED_SECTION", occurrence: 2 }]); });
  it("builds stable validated events and deduplicates history", () => { const source = CHANGE_RADAR_SOURCE_REGISTRY.sources.find((s) => s.lifecycle === "APPROVED_MONITOR")!; const current = hashNormalizedContent("current"); const change = { type: "MODIFIED_SECTION" as const, headingPath: ["API"], occurrence: 1, excerptBefore: "old", excerptAfter: "required migration" }; const a = buildPublicChangeEvent(source, change, { previous: hashNormalizedContent("old"), current }, "2026-09-02T00:00:00.000Z"); const b = buildPublicChangeEvent(source, change, { previous: hashNormalizedContent("old"), current }, "2026-09-03T00:00:00.000Z"); expect(a.id).toBe(b.id); expect(a.impactLevel).toBe("REVIEW_REQUIRED"); expect(retainBoundedHistory([a], [b])).toHaveLength(1); });
  it("allocates discovery capacity fairly and leaves every candidate disabled", async () => { const fetchImpl = async (input: RequestInfo | URL) => { const url = String(input); if (url.endsWith("robots.txt")) return new Response("User-agent: *\nAllow: /", { headers: { "content-type": "text/plain" } }); const prefix = url.includes("platform") ? "https://platform.claude.com/docs/en" : "https://code.claude.com/docs/en"; return new Response(Array.from({ length: 5 }, (_, i) => `${prefix}/candidate-${i}.md`).join("\n"), { headers: { "content-type": "text/plain" } }); }; const result = await discoverDetailed({ fetchImpl: fetchImpl as typeof fetch, perIndexCap: 2, totalCap: 4 }); expect(result.candidates).toHaveLength(4); expect(result.candidates.every((c) => c.enabled === false)).toBe(true); expect(new Set(result.candidates.map((c) => c.discoveredFrom)).size).toBe(2); });
  it("emits at most one first-seen event per source and is idempotent", async () => { const fetchImpl=async(input:RequestInfo|URL)=>{const url=String(input);if(url.endsWith("robots.txt"))return new Response("User-agent: *\nAllow: /",{headers:{"content-type":"text/plain"}});if(url.endsWith(".atom"))return new Response("<feed><title>Service history with enough stable semantic content for comparison</title></feed>",{headers:{"content-type":"application/atom+xml"}});return new Response("<html><main><h1>Release notes</h1><h2>Models</h2><p>Stable official documentation content long enough for semantic validation.</p><h2>API</h2><p>A second section must not create another first-seen event.</p></main></html>",{headers:{"content-type":"text/html",etag:'"stable"'}});};const first=await runRadar({fetchImpl:fetchImpl as typeof fetch,now:()=>new Date("2026-09-02T00:00:00Z")});const healthy=first.health.filter((item)=>item.stage==="HEALTHY").length;expect(first.events).toHaveLength(healthy);expect(first.events.every((event)=>event.changeType==="FIRST_SEEN"&&event.headingPath.join("/")==="Document body")).toBe(true);expect(new Set(first.events.map((event)=>event.sourceId)).size).toBe(first.events.length);const second=await runRadar({fetchImpl:fetchImpl as typeof fetch,previous:first.baselines,now:()=>new Date("2026-09-03T00:00:00Z")});expect(second.events).toEqual([]);expect(Object.values(first.baselines).every((b)=>!("text" in b))).toBe(true);});
  it("rejects malformed event and health fields",()=>{const source=CHANGE_RADAR_SOURCE_REGISTRY.sources.find((s)=>s.lifecycle==="APPROVED_MONITOR")!;const event=buildPublicChangeEvent(source,{type:"ADDED_SECTION",headingPath:["A"],occurrence:1,excerptBefore:null,excerptAfter:"safe"},{previous:null,current:hashNormalizedContent("x")},"2026-09-02T00:00:00.000Z");expect(()=>parsePublicChangeEvent({...event,officialHost:"evil.example"})).toThrow();expect(()=>parsePublicChangeEvent({...event,changeType:"EXECUTE"})).toThrow();expect(()=>parsePublicChangeEvent({...event,excerptAfter:"x".repeat(281)})).toThrow();expect(()=>parseSourceHealth({sourceId:"x",checkedAt:"bad",stage:"HEALTHY",reason:null,statusCode:200})).toThrow();});
});
