export const SYSTEM_STATUS = {
  GREEN: "GREEN",
  YELLOW: "YELLOW",
  RED: "RED",
} as const;

export type SystemStatus = (typeof SYSTEM_STATUS)[keyof typeof SYSTEM_STATUS];

export const RISK_LEVEL = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
} as const;

export type RiskLevel = (typeof RISK_LEVEL)[keyof typeof RISK_LEVEL];

export const AGENT_PERMISSION_MODE = {
  OBSERVE_ONLY: "OBSERVE_ONLY",
  RECOMMEND_ONLY: "RECOMMEND_ONLY",
  EXECUTE_LOW_RISK: "EXECUTE_LOW_RISK",
  HUMAN_APPROVAL_REQUIRED: "HUMAN_APPROVAL_REQUIRED",
  DISABLED: "DISABLED",
} as const;

export type AgentPermissionMode =
  (typeof AGENT_PERMISSION_MODE)[keyof typeof AGENT_PERMISSION_MODE];

export const AGENT_STATUS = {
  HEALTHY: "HEALTHY",
  WATCHING: "WATCHING",
  ATTENTION: "ATTENTION",
  WAITING_FOR_HUMAN: "WAITING_FOR_HUMAN",
  DISABLED: "DISABLED",
} as const;

export type AgentStatus = (typeof AGENT_STATUS)[keyof typeof AGENT_STATUS];

export const INCIDENT_STATUS = {
  DETECTED: "DETECTED",
  INVESTIGATING: "INVESTIGATING",
  DIAGNOSED: "DIAGNOSED",
  REMEDIATION_PROPOSED: "REMEDIATION_PROPOSED",
  AWAITING_APPROVAL: "AWAITING_APPROVAL",
  APPROVED: "APPROVED",
  REMEDIATED: "REMEDIATED",
  RESOLVED: "RESOLVED",
} as const;

export type IncidentStatus =
  (typeof INCIDENT_STATUS)[keyof typeof INCIDENT_STATUS];

export const APPROVAL_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  DENIED: "DENIED",
  EXPIRED: "EXPIRED",
  CONSUMED: "CONSUMED",
} as const;

export type ApprovalStatus =
  (typeof APPROVAL_STATUS)[keyof typeof APPROVAL_STATUS];

export const ACCESS_REQUEST_STATUS = {
  PENDING: "PENDING",
  INSPECTED: "INSPECTED",
  AWAITING_APPROVAL: "AWAITING_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  PROCESSED: "PROCESSED",
} as const;

export type AccessRequestStatus =
  (typeof ACCESS_REQUEST_STATUS)[keyof typeof ACCESS_REQUEST_STATUS];

export const MISSION_MODE = {
  GUIDED: "GUIDED",
  OPERATOR: "OPERATOR",
  INTERVIEW: "INTERVIEW",
} as const;

export type MissionMode = (typeof MISSION_MODE)[keyof typeof MISSION_MODE];

export const MISSION_STATUS = {
  ACTIVE: "ACTIVE",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
} as const;

export type MissionStatus =
  (typeof MISSION_STATUS)[keyof typeof MISSION_STATUS];

export const EVIDENCE_QUALITY = {
  DECISIVE: "DECISIVE",
  USEFUL: "USEFUL",
  DISTRACTION: "DISTRACTION",
} as const;

export type EvidenceQuality =
  (typeof EVIDENCE_QUALITY)[keyof typeof EVIDENCE_QUALITY];

export const EFFORT_LEVEL = {
  STANDARD: "STANDARD",
  HIGH: "HIGH",
} as const;

export type EffortLevel = (typeof EFFORT_LEVEL)[keyof typeof EFFORT_LEVEL];

export const MODEL_ID = {
  OPUS: "opus",
  SONNET: "sonnet",
  HAIKU: "haiku",
} as const;

export type ModelId = (typeof MODEL_ID)[keyof typeof MODEL_ID];

export const DEMO_READINESS = {
  READY: "READY",
  AT_RISK: "AT_RISK",
  NOT_READY: "NOT_READY",
} as const;

export type DemoReadiness =
  (typeof DEMO_READINESS)[keyof typeof DEMO_READINESS];

export const AGENT_OPERATION_KIND = {
  OBSERVE_SIGNAL: "OBSERVE_SIGNAL",
  RUN_PREFLIGHT: "RUN_PREFLIGHT",
  RUN_READ_ONLY_DIAGNOSTIC: "RUN_READ_ONLY_DIAGNOSTIC",
  CLASSIFY_EVENT: "CLASSIFY_EVENT",
  DRAFT_RUNBOOK: "DRAFT_RUNBOOK",
  DRAFT_POSTMORTEM: "DRAFT_POSTMORTEM",
  CREATE_PROPOSED_CHANGE: "CREATE_PROPOSED_CHANGE",
  CHANGE_ROLE: "CHANGE_ROLE",
  CHANGE_MODEL_ENTITLEMENT: "CHANGE_MODEL_ENTITLEMENT",
  ROTATE_CREDENTIAL: "ROTATE_CREDENTIAL",
  REAUTHORIZE_CONNECTOR: "REAUTHORIZE_CONNECTOR",
  REACTIVATE_USER: "REACTIVATE_USER",
  DEPROVISION_USER: "DEPROVISION_USER",
  CHANGE_ORG_CONFIGURATION: "CHANGE_ORG_CONFIGURATION",
  GRANT_WRITE_TOOL_ACCESS: "GRANT_WRITE_TOOL_ACCESS",
  CHANGE_POLICY: "CHANGE_POLICY",
  ACCEPT_DOCUMENTATION_UPDATE: "ACCEPT_DOCUMENTATION_UPDATE",
} as const;

export type AgentOperationKind =
  (typeof AGENT_OPERATION_KIND)[keyof typeof AGENT_OPERATION_KIND];

export const ACTION_PHASE = {
  OBSERVE: "OBSERVE",
  RECOMMEND: "RECOMMEND",
  PROPOSE: "PROPOSE",
  APPROVE: "APPROVE",
  EXECUTE: "EXECUTE",
  VERIFY: "VERIFY",
} as const;

export type ActionPhase = (typeof ACTION_PHASE)[keyof typeof ACTION_PHASE];

export const DOMAIN_EVENT_TYPE = {
  INCIDENT_CREATED: "INCIDENT_CREATED",
  INVESTIGATION_STEP: "INVESTIGATION_STEP",
  DIAGNOSIS_CONFIRMED: "DIAGNOSIS_CONFIRMED",
  REMEDIATION_PROPOSED: "REMEDIATION_PROPOSED",
  APPROVAL_REQUESTED: "APPROVAL_REQUESTED",
  APPROVAL_GRANTED: "APPROVAL_GRANTED",
  APPROVAL_DENIED: "APPROVAL_DENIED",
  REMEDIATION_EXECUTED: "REMEDIATION_EXECUTED",
  REMEDIATION_VERIFIED: "REMEDIATION_VERIFIED",
  VERIFICATION_FAILED: "VERIFICATION_FAILED",
  DEMO_AT_RISK: "DEMO_AT_RISK",
  DEMO_READY: "DEMO_READY",
  PREFLIGHT_COMPLETED: "PREFLIGHT_COMPLETED",
  ACCESS_REQUEST_UPDATED: "ACCESS_REQUEST_UPDATED",
  AGENT_ACTION_PROPOSED: "AGENT_ACTION_PROPOSED",
  AGENT_ACTION_EXECUTED: "AGENT_ACTION_EXECUTED",
  AGENT_ACTION_DENIED: "AGENT_ACTION_DENIED",
  GATEWAY_DECISION_EVALUATED: "GATEWAY_DECISION_EVALUATED",
  MISSION_EVENT: "MISSION_EVENT",
} as const;

export type DomainEventType =
  (typeof DOMAIN_EVENT_TYPE)[keyof typeof DOMAIN_EVENT_TYPE];
