import { parsePublicChangeEvent } from "@/lib/change-radar/schema";
import type { LoopContract, LoopRun } from "./types";

export const GOLDEN_LOOP_CONTRACT: LoopContract = {
  id: "contract:model-entitlement",
  version: 1,
  goal: "Turn an accepted model-entitlement observation into a verified, reviewable runbook improvement.",
  trigger: "An authored model-entitlement fixture changes and a human accepts it for synthetic assessment.",
  accountableHuman: "maya",
  ownerId: "maya",
  backupOwnerId: "leila",
  reviewerId: "aisha",
  approverId: "mateo",
  verificationPlanApproverId: "aisha",
  runbookApproverId: "mateo",
  closureApproverId: "priya",
  verificationAgentId: "verification-agent",
  handoff: { situation: "The authored entitlement fixture now requires an access check before rehearsal.", impact: "A fictional demo may request an unavailable model; its preflight and learning material need review.", nextAction: "Claim ownership, approve the bounded plan, then run the synthetic entitlement preflight.", rollback: "Retain runbook v1 until an approved v2 passes replay.", evidence: ["Authored before/after wording in change:bffcb5c9f00cf34956139cad9c3718e3", "Recorded public release-note reference; operational impact remains inferred"] },
  permittedAgentActions: ["RUN_VERIFICATION"],
  humanRequiredDecisions: ["ACCEPT_CHANGE", "CLAIM_WORK", "APPROVE_MISSION", "APPROVE_VERIFICATION_PLAN", "APPROVE_LEARNING", "CLOSE_LOOP", "RESET"],
  evidenceRequirements: ["recorded public reference", "authored fixture diff", "synthetic effective-access receipt"],
  verificationChecks: ["requested model is effectively entitled", "fallback remains available"],
  maximumAttempts: 2,
  executionBudgetMs: 1_000,
  timeBudgetMinutes: 30,
  stopConditions: ["maximum attempts reached", "verification evidence unavailable"],
  escalationConditions: ["missing owner or backup", "failed replay", "authority boundary reached"],
  rollback: "Retain immutable runbook v1 and withdraw v2 from active use.",
  safeFallback: "Use the entitled synthetic Sonnet profile; make no entitlement change.",
  learningOutputPolicy: "Only a human-approved lesson may become an immutable runbook version.",
};

const REHEARSAL_EVENT = parsePublicChangeEvent({
  id: "change:bffcb5c9f00cf34956139cad9c3718e3",
  sourceId: "platform-release-notes",
  sourceTitle: "Claude Platform release notes",
  canonicalUrl: "https://platform.claude.com/docs/en/release-notes/overview",
  sourceKind: "RELEASE_NOTES" as const,
  officialHost: "platform.claude.com",
  productSurface: "Claude Platform",
  fetchedAt: "2026-09-02T18:00:00.000Z",
  publishedAt: null,
  detectedAt: "2026-09-02T18:00:00.000Z",
  previousHash: "675c906ff12f8ec6e8a1d876adc6872825f1175f43f0c9a474b7ff6859e10308",
  currentHash: "7bfe97dcebedd0a75098b35b75861137a7e4f24e414d4c4756e9400a6e5f388f",
  etag: null,
  lastModified: null,
  changeType: "MODIFIED_SECTION" as const,
  headingPath: ["Models", "Availability", "Entitlement prerequisites"],
  headingOccurrence: 1,
  excerptBefore: "Model selection is checked during rehearsal setup.",
  excerptAfter: "Effective model entitlement must be checked before a rehearsal begins.",
  observedFacts: [
    "Authored fixture input changed at Models > Availability > Entitlement prerequisites (occurrence 1); not an observed public-page change.",
  ],
  inferredImpactDomains: ["model governance", "AI gateway"],
  affectedSyntheticAssets: ["system:model-governance", "agent:preflight", "runbook:model-access", "test:effective-access", "briefing:AI gateway"],
  impactLevel: "REVIEW_REQUIRED" as const,
  classificationConfidence: 0.92,
  reviewState: "DETECTED" as const,
  ownerId: "demo-systems-administrator",
  reviewerIds: [],
  proposedActions: ["Human review required before any operational change."],
  evidenceReceiptId: "receipt:bffcb5c9f00cf34956139cad9c3718e3",
});

const REHEARSAL_CHANGE = {
  ...REHEARSAL_EVENT,
  title: "Model entitlement documentation change",
  scenario: "DETERMINISTIC_REHEARSAL" as const,
  evidence: [
    { label: "OBSERVED" as const, value: "Recorded fixture input only. These entitlement sentences were authored for this lab, not observed on the official page.", sourceId: "platform-release-notes" },
    { label: "DERIVED" as const, value: "The two authored inputs have different normalized SHA-256 hashes; this is not evidence of a live page change." },
    { label: "INFERRED" as const, value: "The synthetic demo preflight may require a compatibility control." },
    { label: "PROPOSED" as const, value: "Rehearse effective model access before changing the runbook." },
    { label: "SYNTHETIC" as const, value: "The workspace, demo, entitlement, people, and verification result are fictional." },
  ],
};

export function createGoldenLoopRun(contract: LoopContract = GOLDEN_LOOP_CONTRACT): LoopRun {
  return {
    id: "loop:model-entitlement",
    phase: "OBSERVED",
    contract,
    change: REHEARSAL_CHANGE,
    reviewDecision: null, mission: null, workItem: null, verificationPlan: null,
    receipts: [], learningRecord: null,
    runbookVersions: [{ id: "runbook:model-access:v1", previousVersionId: null, version: 1, immutable: true, approvedBy: "mateo", approvedAt: "2026-08-25T14:00:00.000Z", learningRecordId: null, expectedEntitlement: "claude-opus" }],
    affectedRunbook: null,
    closedBy: null,
    activeRunbookVersionId: "runbook:model-access:v1",
    currentAttempt: 0,
    escalated: false,
    stopReason: null,
    escalationReason: null,
    audit: [],
    processedActionIds: [],
  };
}
