import { CHANGE_RADAR_SOURCES, isSourceUrlAllowed } from "../../data/change-radar/registry.ts";
import { fetchRadarSource } from "./fetch.ts";
export interface DiscoveryCandidate { url: string; discoveredFrom: string; enabled: false; }
export interface DiscoveryResult { candidates: DiscoveryCandidate[]; counts: { discoveredFrom: string; discovered: number; retained: number; truncated: number }[]; }
export function extractMarkdownCandidates(indexText: string, indexUrl: string): string[] { const base = new URL(indexUrl); const matches = indexText.match(/https:\/\/[^\s)>"']+\.md(?:#[^\s)>"']*)?|\/[^\s)>"']+\.md(?:#[^\s)>"']*)?/g) ?? []; return [...new Set(matches.map((value) => new URL(value.replace(/#.*$/, ""), base).toString()))].sort(); }
export async function discoverDetailed(options: { fetchImpl?: typeof fetch; perIndexCap?: number; totalCap?: number } = {}): Promise<DiscoveryResult> { const perIndexCap = options.perIndexCap ?? 125; const totalCap = options.totalCap ?? 250; const enabled = new Set(CHANGE_RADAR_SOURCES.filter((s) => s.lifecycle === "APPROVED_MONITOR").map((s) => s.canonicalUrl)); const indexes = CHANGE_RADAR_SOURCES.filter((s) => s.lifecycle === "DISCOVERY_INDEX").sort((a, b) => a.id.localeCompare(b.id)); const buckets: DiscoveryCandidate[][] = []; const counts: DiscoveryResult["counts"] = [];
  for (const source of indexes) { try { const fetched = await fetchRadarSource(source, null, { fetchImpl: options.fetchImpl, retries: 1 }); const all = fetched.body ? extractMarkdownCandidates(fetched.body, source.canonicalUrl).filter((url) => isSourceUrlAllowed(source, url) && !enabled.has(url)) : []; const selected = all.slice(0, perIndexCap).map((url) => ({ url, discoveredFrom: source.id, enabled: false as const })); buckets.push(selected); counts.push({ discoveredFrom: source.id, discovered: all.length, retained: 0, truncated: Math.max(0, all.length - selected.length) }); } catch { buckets.push([]); counts.push({ discoveredFrom: source.id, discovered: 0, retained: 0, truncated: 0 }); } }
  const candidates: DiscoveryCandidate[] = []; for (let index = 0; candidates.length < totalCap; index += 1) { let added = false; for (const bucket of buckets) if (bucket[index] && candidates.length < totalCap) { const candidate=bucket[index]; candidates.push(candidate); const count=counts.find((item)=>item.discoveredFrom===candidate.discoveredFrom)!; count.retained+=1; added = true; } if (!added) break; } for(const count of counts) count.truncated=count.discovered-count.retained; return { candidates, counts }; }
export async function discover(fetchImpl: typeof fetch = fetch) { return (await discoverDetailed({ fetchImpl })).candidates; }
