import type { ChangeRadarSource, PublicChangeEvent } from "../../lib/change-radar/types.ts";
import { parsePublicChangeEvent } from "../../lib/change-radar/schema.ts";
import type { SectionChange } from "./diff.ts";
import { stableEventId } from "./hash.ts";
import { classifyDeterministically, parsePublishedAt } from "./classify.ts";
import { mapImpact } from "./impact-map.ts";
export const HISTORY_LIMIT = 100;
export function retainBoundedHistory<T>(history: readonly T[], additions: readonly T[], limit = HISTORY_LIMIT): T[] { const keyed = new Map<string, T>(); for (const item of [...history, ...additions]) keyed.set(typeof item === "object" && item && "id" in item ? String(item.id) : JSON.stringify(item), item); return [...keyed.values()].slice(-limit); }
export function buildPublicChangeEvent(source: ChangeRadarSource, change: SectionChange, hashes: { previous: string | null; current: string }, at: string, metadata: { etag?: string | null; lastModified?: string | null } = {}): PublicChangeEvent { const evidence = [change.excerptAfter, change.excerptBefore].filter(Boolean).join(" "); const classification = classifyDeterministically(evidence); const id = stableEventId([source.id, hashes.previous ?? "FIRST_SEEN", hashes.current, change.type, change.headingPath.join("/"), String(change.occurrence)]); return parsePublicChangeEvent({ id, sourceId: source.id, sourceTitle: source.title, canonicalUrl: source.canonicalUrl, sourceKind: source.sourceKind, officialHost: new URL(source.canonicalUrl).hostname, productSurface: source.productSurface, fetchedAt: at, publishedAt: parsePublishedAt(evidence), detectedAt: at, previousHash: hashes.previous, currentHash: hashes.current, etag: metadata.etag ?? null, lastModified: metadata.lastModified ?? null, changeType: hashes.previous ? change.type : "FIRST_SEEN", headingPath: change.headingPath, headingOccurrence: change.occurrence, excerptBefore: change.excerptBefore, excerptAfter: change.excerptAfter, observedFacts: [`Official source content ${hashes.previous ? "changed" : "was first observed"} at ${change.headingPath.join(" > ")} (occurrence ${change.occurrence}).`], inferredImpactDomains: [...source.operationalDomains], affectedSyntheticAssets: mapImpact(source.operationalDomains), impactLevel: classification.impactLevel, classificationConfidence: classification.confidence, reviewState: "DETECTED", ownerId: source.expectedOwner, reviewerIds: [], proposedActions: ["Human review required before any operational change."], evidenceReceiptId: `receipt:${id.slice(7)}` }); }
